version: 0.2
phases:
  install: 
    commands:
           - pip install --upgrade pip
           - pip install -r requirements.txt pylint
           - pip manage.py loaddata project_dump.json
    pre_build:
        commands:
           - python --version
           - pylint $CODEBUILD_SRC_DIR/*.py
    artifacts:
      files:
         - '**/*'
