version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - python3 -m venv env
      - chmod +x ./env/bin/activate
      - pip install --upgrade pip --disable-pip-version-check 
      - pip install pylint==2.11.1
      - pip install pylint-json2html==0.4.0
      #- pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Running Pylint static code analysis"
      - which pylint
      - pylint --output-format=json --fail-under=0 $CODEBUILD_SRC_DIR/contacts/*.py> pylint_report.json || true
      - pylint-json2html -f json -o pylint_report.html pylint_report.json
      - echo "Static code analysis report generated"
      - sudo apt-get install wget
      - curl -o pylint_report.html <URL to the report>

      #- wget <URL to the report> -O pylint_report.html
      #$CODEBUILD_SRC_DIR/*.py $CODEBUILD_SRC_DIR/accounts/*.py $CODEBUILD_SRC_DIR/autozone/*.py $CODEBUILD_SRC_DIR/cars/*.py
    
  build:
    commands:
      - echo "Running Django migrations"
      - python manage.py migrate --traceback
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput
      #- echo "loading data from project_dump"
      #- python manage.py loaddata project_dump.json
    commands:
      - echo Build completed on `date`

artifacts:
    files:
      - '**/*'