version: 0.2
phases:
  install: 
    commands:
           - pip install --upgrade pip
           - pip install -r requirements.txt
    pre_build:
        commands:
           - python --version
    artifacts:
      files:
         - '**/*'
