version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - python3 -m venv env
      - chmod +x ./env/bin/activate
      - pip install --upgrade pip --disable-pip-version-check 
      - pip install pylint==2.11.1
      - pip install pylint-json2html==0.4.0
      - pip install -r requirements.txt
      - sudo apt-get install jq
      - sudo apt-get update
      #- sudo apt-get install -y bsdmainutils
      - pip install tabulate
      - sudo apt-get install bash-builtins


  pre_build:
    commands:
      - echo "Running Pylint static code analysis"
      - which pylint
      - pylint --output-format=json --fail-under=0 $CODEBUILD_SRC_DIR/contacts/*.py $CODEBUILD_SRC_DIR/*.py $CODEBUILD_SRC_DIR/accounts/*.py $CODEBUILD_SRC_DIR/autozone/*.py $CODEBUILD_SRC_DIR/cars/*.py > pylint_report.json || true
      #- pylint-json2html -f json -o pylint_report.html pylint_report.json
      - echo "Static code analysis report generated"
      - cat pylint_report.json | jq -r '.[] | [ .module, .type, .message ] | @tsv' | sed 's/[[:space:]]\{2,\}/ /g' | (echo -e "Module\tType\tMessage" && python -c "import sys, tabulate; print(tabulate.tabulate([line.strip().split('\t') for line in sys.stdin]))")
      #- cat pylint_report.json | jq
      - echo 'THIS pre_build STAGE MIGHT BE SUCCEDED. PLEASE CHECK CODE BUILD LOGS FOR STATIC CODE ANALYSIS'
      #- aws s3 cp pylint_report.html s3://codepipeline-eu-west-2-613623979028/x21171203-devsecops-/static-code-analysis/pylint_report.html --debug
      
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/

  build:
    commands:
      - echo "Running Django migrations"
      - python manage.py migrate --traceback
      - echo "Collecting static files"
      - sudo apt install default-jre -y
      - java --version
      - python manage.py collectstatic --noinput     
      - ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.login=08757a4d0fb1dbc93898fa08dfe71dfe32aea043 -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=devsecopsautozone -Dsonar.organization=devsecopsautozone
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=devsecopsautozone >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi

artifacts:
    files:
      - '**/*'
