version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - python3 -m venv env
      - chmod +x ./env/bin/activate
      - pip install --upgrade pip --disable-pip-version-check
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Django migrations"
      - python manage.py migrate
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput
artifacts:
  files:
    - '**/*'
  name: my-django-app