version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - python3 -m venv env
      - chmod +x ./env/bin/activate
      - pip install --upgrade pip --disable-pip-version-check 
      - pip install pylint==2.11.1
      - pip install pylint-json2html==0.4.0
      - pip install -r requirements.txt
      - sudo apt-get install jq
  
  pre_build:
    commands:
      - echo "Running Pylint static code analysis"
      - which pylint
      - pylint --output-format=json --fail-under=0 $CODEBUILD_SRC_DIR/contacts/*.py> pylint_report.json || true
      - echo "Static code analysis report generated"
      - cat pylint_report.json | jq
      #- aws s3 cp pylint_report.html s3://codepipeline-eu-west-2-613623979028/x21171203-devsecops-/static-code-analysis/pylint_report.html --debug
      #$CODEBUILD_SRC_DIR/*.py $CODEBUILD_SRC_DIR/accounts/*.py $CODEBUILD_SRC_DIR/autozone/*.py $CODEBUILD_SRC_DIR/cars/*.py
    
  build:
    commands:
      - echo "Running Django migrations"
      - python manage.py migrate --traceback
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput
      #- echo "loading data from project_dump"
      #- python manage.py loaddata project_dump.json
    commands:
      - echo Build completed on `date`

artifacts:
    files:
      - '**/*'