branch-defaults:
  main:
    environment: x21171203-devsecops-autozone-ebs-env
    group_suffix: null
global:
  application_name: x21171203-devsecops-autozone-ebs-application
  branch: null
  default_ec2_keyname: x21171203-devsecops-autozone-kp
  default_platform: Python 3.7
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: MSCCLOUD-250738637992
  repository: null
  sc: git
  workspace_type: Application
